name: lodestar-git-api
development: true

servicePort: 8080

imageName: "lodestar-git-api"
imageTag: "latest"

builderImage: registry.access.redhat.com/ubi8/openjdk-11
builderImageTag: 1.3

git:
  uri: https://github.com/rht-labs/lodestar-git-api.git
  ref: master

configRepositoryId: false
deployKey: false
gitLabApiUrl: false
gitLabPersonalAccessToken: false
engagementsRepositoryId: false

config:
  hookFile:
    path: /runtime
    name: webhooks.yaml
  hooks:
    - name: hook1
      baseUrl: http://localhost/hook1
      token: ibaka
    - name: hook2
      baseUrl: http://localhost/hook2
      token: anunoby

